# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('H', 'Huddle Room'), ('T', 'Team Room'), ('C', 'Conference Room')], max_length=1)),
                ('floor', models.IntegerField(choices=[(1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor')])),
                ('lan', models.BooleanField()),
                ('phone', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('video_conferencing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roombooking.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
